package com.demo.cashierapp.exception;

public enum ErrorSubtype {
    // EMPLOYEE ERROR TYPES
    USERNAME_EXISTS,
    USERNAME_DOES_NOT_EXIST,
    MISSING_FIRST_NAME,
    MISSING_LAST_NAME,
    MISSING_USERNAME,
    MISSING_PASSWORD,
    PASSWORD_IS_INVALID,
    INCORRECT_PASSWORD,
    MISSING_ROLE,

    // PRODUCT ERROR TYPES
    MISSING_SUPPLIER_NAME,
    MISSING_BRAND,
    MISSING_BARCODE,
    MISSING_PRODUCT_NAME,
    MISSING_PRODUCT_DESCRIPTION,
    MISSING_MEASUREMENT,
    NEGATIVE_VALUE,
    BARCODE_DOES_NOT_EXIST,
    SUPPLIER_DOES_NOT_EXIST,

    //SUPPLIER ERROR TYPES
    NAME_EXISTS,
    NAME_DOES_NOT_EXIST,
    MISSING_NAME,
    MISSING_CONTACT_NAME,
    MISSING_PHONE,
    MISSING_ADDRESS

}
