package com.demo.cashierapp.exception;

public enum ErrorSubtype {
    // EMPLOYEE ERROR TYPES
    USERNAME_EXISTS,
    USERNAME_DOES_NOT_EXIST,
    MISSING_FIRST_NAME,
    MISSING_LAST_NAME,
    MISSING_USERNAME,
    MISSING_PASSWORD,
    MISSING_ROLE,

    // PRODUCT ERROR TYPES
    MISSING_SUPPLIER_NAME,
    MISSING_BRAND,
    MISSING_BARCODE,
    MISSING_PRODUCT_NAME,
    MISSING_PRODUCT_DESCRIPTION,
    MISSING_MEASUREMENT,
    NEGATIVE_VALUE,
    BARCODE_DOES_NOT_EXIST,
    SUPPLIER_DOES_NOT_EXIST

}
